#! /usr/bin/python

#	This is a plugin developed for gphpedit a php editor
#	Author : Vipin S <svipinsaji@gmail.com>
#	Version : 1
# 	The file must be saved for the plugin to work and the last saved instance of the plugin will be used
#	for more details on installation of the plugin, read the readme distributed along with the plugin




import sys

# plugin details to be fed to gphpedit

if sys.argv[1].strip()=='-name':
	print "Status"
elif sys.argv[1].strip()=="-desc":
	print "Plugin to show the statistics of the file" 
elif sys.argv[1].strip()=="-icon":
	print "../test.png"	
elif sys.argv[1].strip()=="-copyright":
	print "GPL3"
elif sys.argv[1].strip()=="-website":
	print "http://www.gphpedit.com"
elif sys.argv[1].strip()=="-version":
	print "1.1"
elif sys.argv[1].strip()=="-authors":
	print"Vipin"
elif sys.argv[1].strip()=="-type":
	print "FNAME"
else:
	sys.path.extend(['./../conf/','/usr/share/gphpedit/conf/','~/.gphpedit/conf/'])
	import statconf
	import statmodule
	f=open(sys.argv[1],"r")
	lines=[]
	for line in f:
		if not(statconf.BlankLineCount):
			if line.strip():
				lines.append(line)
		else:
			lines.append(line)	
	if lines: lines=statmodule.commentmanager(lines,sys.argv[1])			
	string=statmodule.messagemanager(lines)	
	del sys.path[len(sys.path)-3:]	
	print "MESSAGE\n"+string
